platform :ios, '8.0'
inhibit_all_warnings!

target 'BaseProject' do
    pod 'AFNetworking'
    pod 'MJExtension'
    pod 'MJRefresh'
    pod 'YYKit'
    pod 'WXSTransition'
    pod 'MBProgressHUD'
    pod 'SVProgressHUD'
    pod 'AMapLocation-NO-IDFA'
    pod 'AMapSearch-NO-IDFA'
    pod 'AMap2DMap-NO-IDFA'
    pod 'TZImagePickerController'
    pod 'MWPhotoBrowser'
    pod ‘UMengUShare/UI’
    pod ‘UMengUShare/Social/ReducedWeChat'
    pod ‘UMengUShare/Social/ReducedQQ'
end
